version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      # dockerfile: Dockerfile    
    #deploy:
    #  replicas: 2
    container_name: myfrontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks: 
      - lemoncode-challenge
  backend:
    build: 
      context: ./backend/backend      
    container_name: mybackend
    ports:
      - 5000:80
    depends_on:
      - mongodb
    networks: 
      - lemoncode-challenge
  mongodb:
    image: mongo:latest
    container_name: mymongo
    ports:
      - 27017:27017
    volumes: 
      - mongo-volume:/data/db
    networks: 
      - lemoncode-challenge
volumes:
    mongo-volume:
networks:
    lemoncode-challenge: