apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todoapp
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todoapp
    spec:
      containers:
      - image: atobajas/lc-todo-monolith
        name: lc-todo-monolith
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        # Es información para el sistema.
        ports:
        - containerPort: 8080
        # Prueba de vida para el contenedor de este pod
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todoapp
  name: todoapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todoapp
  type: LoadBalancer
status:
  loadBalancer: {}