apiVersion: v1
kind: Service
metadata:
  name: todo-sql-svc
  labels:
    app: todo-sql-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: todo-sql
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: todo-sql
  name: todo-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-sql
  serviceName: "todo-sql-svc"
  template:
    metadata:
      labels:
        app: todo-sql
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim