apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
      app: postgres
spec:
  storageClassName: localstorage
  # sólo un pod puede escribir a la vez.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi