apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  # https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/c/postgres"
    type: DirectoryOrCreate
