apiVersion: v1
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: todo-sql-svc
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: "5432"
  DB_NAME: todos_db
  DB_VERSION: "10.4"
kind: ConfigMap
metadata:
  name: envconfig
  labels:
    app: todoapp